#!/bin/bash

if [ -z "$conf_file" ]; then
	conf_file='/etc/pssh2.conf'
fi

usage()
{
cat << EOT
NAME
  build_hhblits_structure_profile - generate a hhblits aligment file (called a3m) for a pdb sequence
SYNOPSIS
  build_hhblits_structure_profile  [-s] [-h] [-D]  <-p pathToWorkOn> 
DESCRIPTION
  build_hhblits_profile takes an input sequence,
  calls build_hhblits_profile to scan agains uniprot20 and generate an a3m alignment, 
  then it  runs addss.pl on the a3m file (based on the best pdb structure for the sequence),
  producing a new a3m file including the secondary structure.
  Any input behind "--" is passed on build_hhblits_profile 
OPTIONS
  -h          The option -h displays help and exits.
  -D          Debug option: do not remove or zip output files
  -s          Operate silently 
AUTHOR
  Andrea Schafferhans <andrea.schafferhans@rostlab.org>
EOT
exit 1
}

debug=0
passOpt=" " 
while getopts :Dhm: opt
do
	case $opt in
	D) debug=1;; 
	h) usage; echo " "; build_hhblits_profile -h; exit;;
	p) path=$OPTARG;;
	esac
done

if [ $debug -eq 1 ]
then
	set -x
fi

shift $(expr $OPTIND - 1 )
passOpt="$passOpt $@"

### TODO


count=0
DB.pssh2_local "insert into pssh2_local.$status_table set md5=\"$md5\" , count=$count , stamp=$s , runtime=0" 
