#!/bin/bash

if [ -z "$conf_file" ]; then
	conf_file='/etc/pssh2.conf'
fi

### parameters

# get configurable options, e.g. local file paths
if [ -s $conf_file ]
then
	source $conf_file
fi

usage()
{
cat << EOT
NAME
  find_best_pdb_for_seqres_md5 - find a pdb code and chain that best represents the SEQRES sequence 
SYNOPSIS
  find_best_pdb_for_seqres_md5 <-m md5> 
DESCRIPTION
  build_hhblits_profile takes an input sequence,
  calls build_hhblits_profile to scan agains uniprot20 and generate an a3m alignment, 
  then it  runs addss.pl on the a3m file (based on the best pdb structure for the sequence),
  producing a new a3m file including the secondary structure.
  Any input behind "--" is passed on build_hhblits_profile 
OPTIONS
  -h          The option -h displays help and exits.
  -D          Debug option: do not remove or zip output files
  -F n        Set force remaking status for making of HMM profile (run build_hhblits_profile):
     0           do not make profile unless none exists
     1           run only if the profile is older than the last update of uniprot20 (default)
     2           always run, even if the profile exists 
  -R          Retain (DO NOT remake) the HMM profile (same as -F 0)
  -s          Operate silently 
AUTHOR
  Andrea Schafferhans <andrea.schafferhans@rostlab.org>
EOT
exit 1
}
