#!/bin/bash

# rewrite of make_new_pdb_full (just call the general make_new_hhblitsdb)
# this script works based on the pdb table in the mysql database
# (-> extracting SEQRES and redundancy reduction are delegated to the database import)
# it writes the output a3m files to the cache and also adds psipred a3m files to the chache
# then it collects the current psipred a3m files to a directory that hhblitsdb.pl can work on

qsubFlag='-e /mnt/project/pssh/pssh2_project/work/log_pdbFull/ -o /mnt/project/pssh/pssh2_project/work/log_pdbFull/'
if [ -z "$conf_file" ]
then
	conf_file='/etc/pssh2.conf'
else
	# make sure we pass on the conf file if there was one
	# CAVE: THis must be accessible on the queue!
	qsubFlag="$qsubFlag -v conf_file=$conf_file"
fi
echo "conf_file: $conf_file, qsubFlag: $qsubFlag"

usage()
{
cat << EOT
NAME
  make_new_hhblits_db_pdbFull - generate a new pdb_full database 
SYNOPSIS
  make_new_hhblits_db_pdbFull <-m md5List> [-d dbVersion]
DESCRIPTION
  make_new_hhblits_db_pdbFull iterates over sequences given in the md5List (coming fron the pdb table of Aquaria),
  see make_new_hhblits_db for more info
  Any input behind "--" is passed on build_hhblits_structure_profile 
OPTIONS
  -d          output name for new pdb_full (default: current)
  -m          file containing pdb Seqres md5s to run over 
  -h          print this help and exit
  -D          give debug output (passed on to child scripts)
AUTHOR
  Andrea Schafferhans <andrea.schafferhans@rostlab.org>
EOT
exit 1
}
