#!/bin/bash

# rewrite of renew_pdb_full
# this script works based on the pdb table in the mysql database
# (-> extracting SEQRES and redundancy reduction are delegated to the database import)
# it writes the output a3m files to the cache and also adds psipred a3m files to the chache
# then it collects the current psipred a3m files to a directory that hhblitsdb.pl can work on

qsubFlag='-e /mnt/project/pssh/pssh2_project/work/log_pdbFull/ -o /mnt/project/pssh/pssh2_project/work/log_pdbFull/'
if [ -z "$conf_file" ]
then
	conf_file='/etc/pssh2.conf'
else
	# make sure we pass on the conf file if there was one
	# CAVE: THis must be accessible on the queue!
	qsubFlag="$qsubFlag -v conf_file=$conf_file"
fi
echo "conf_file: $conf_file, qsubFlag: $qsubFlag"

usage()
{
cat << EOT
NAME
  make_new_hhblits_db - generate a new hhblits database (for any set of sequences) 
SYNOPSIS
  make_new_hhblits_db <-m md5List> [-d dbName]
DESCRIPTION
  make_new_hhblits_db iterates over sequences given in the md5List,
  runs build_hhblits_profile for each sequence (to get a3m files),
  runs addss.pl on each a3m file (based on the best pdb structure for the sequence),
  links the output a3m files to the psipred a3m directory
  and finally runs hhblitsdb.pl on the psipred a3m directory.
  This script assumes that the sequences given in the md5List are valid sequences,
  any sorting out of DNA sequences, short sequences or some with too many non-amino acid residues
  must happen in the process that constructs the md5List. 
  Any input behind "--" is passed on build_hhblits_structure_profile 
OPTIONS
  -n          name for hhblits database (default: hhblitsdb)
  -d          output name for subdirectory of hhblits database, i.e. dated version (default: current)
  -m          file containing md5s to run over 
  -h          print this help and exit
  -D          give debug output (passed on to child scripts)
AUTHOR
  Andrea Schafferhans <andrea.schafferhans@rostlab.org>
EOT
exit 1
}


# parameters (will be overwritten by anything read from conf file or the command line)
dbName='hhblitsdb'   # for pdbFull this is pdb_full
dbVersion='current'  # for pdbFull this has been db_yyyymmdd
rootDir="/mnt/project/pssh/pssh2_project/" 
n_queue=10
queue_max_wait=1000
build_hhblits_structure_profile='build_hhblits_structure_profile'

#util_dir=$rootDir"src/util/"
#pa3mfile='query.uniprot20.psipred.a3m' 
#source_dir=$rootDir"src/pdb_full/"

# get configurable options, e.g. local file paths
if [ -s $conf_file ]
then
	source $conf_file
fi

# by default we want to use the system installation
# but if local_paths is set we have the option to change the path and instead use the local variants
if [ $local_paths ]
then
	PATH=$local_paths:$PATH
	export PATH
	echo "Using path: $PATH"
	build_hhblits_structure_profile=`which $build_hhblits_structure_profile`
	echo "Using $build_hhblits_structure_profile"
fi

debug=0
passOpt=" " 
while getopts :m:n:d:Dh opt
do
	case $opt in
	D) debug=1; passOpt="$passOpt -D";;
	m) md5ListFile=$OPTARG;;
	n) dbName=$OPTARG;;	
	d) dbDate=$OPTARG;;
	h) usage; build_hhblits_structure_profile -h; exit;;
	:)  echo "Error: -$OPTARG requires an argument"; usage; exit 1;;
#	*) passOpt="$passOpt -$opt";;
	esac
done

if [ $debug -eq 1 ]
then
	set -x
fi


hhblitsdb_result_dir=$rootDir"data/"$dbName
hhblitsdb_data_dir=$rootDir"data/"$dbName"_workData"  # for pdb_full this has been pdb_derived

shift $(expr $OPTIND - 1 )
passOpt="$passOpt $@"


if [ ! -s $md5ListFile ]
then
	echo The file of md5 numbers to iterate over does not exist or is empty
	exit 1
fi

if [ -z $pa3mdir ]
then
	# if the output directory hadn't been set before, we set it now
	pa3mdir=$hhblitsdb_data_dir"/psipred_a3m/"$dbDate"/"
	mkdir $pa3mdir 2>/dev/null
fi

if [ -w $pa3mdir ]
then
	echo "will link psipred a3ms to $pa3mdir"
else
	echo "ERROR: cannot write to output directory $pa3mdir. Please fix!"
	exit 1
fi


## loop over all md5s 
# submit further processing to the queue  
while read md5
do
	if [ -z "${md5// }" ]
	then
		break
	fi
	qsub $qsubFlag $build_hhblits_structure_profile -m $md5 -p $pa3mdir $passOpt		
	# check whether the queue is too full (> 10000 jobs waiting)
	# if yes, sleep a litle before we submit more
	n_waiting=1001
	sleep_time=0 
	while [ $n_waiting -gt $queue_max_wait ]
	do
		sleep $sleep_time
		n_waiting=`qstat -u $USER | grep qw | wc -l` 		
		sleep_time=$((n_waiting/n_queue)) 
	done 

done < $md5ListFile

## when all is done, loop over the md5s again and make links in the psipred_a3m_dir
#while read md5
#do
#	cachePath=`$util_dir/find_cache_path -m $md5`
#	ln -s $cachePath/$pa3mfile $psipred_a3m_dir/$md5.a3m	
#done < $md5ListFile

# wait until all jobs are finished
n_in_queue=1
sleep_time=0
while [ $n_in_queue -gt 0 ]
do
	sleep $sleep_time
	n_in_queue=`qstat -u $USER | wc -l` 		
	sleep_time=$((n_in_queue/n_queue)) 
	if [ $sleep_time -lt 10 ]
	then
		sleep_time=10
	fi
done 


## Generating pdb_full database files with HH-suite script hhblitsdb.pl and the MSAs with PSIPRED prediction received in last step 
db=$hhblitsdb_result_dir"/"$dbVersion
rm -r $db 2>/dev/null #delete old db files
mkdir $db 2>/dev/null

hhblitsdb_log_dir=$rootDir"work/log_hhblitsdb/"
mkdir $hhblitsdb_log_dir 2>/dev/null
if $verbose ;
then
    echo calling hhblitsdb.pl on $pa3mdir "(see log in $hhblitsdb_log_dir)" 
    echo $HHLIB/scripts/hhblitsdb.pl -o $db/$dbName -ia3m $pa3mdir -cpu 10 -log $hhblitsdb_log_dir/hhblitsdb_$dbName_$dbVersion.log
fi  
$HHLIB/scripts/hhblitsdb.pl -o $db/pdb_full -ia3m $pa3mdir -cpu 10 -log $hhblitsdb_log_dir/hhblitsdb_$dbName_$dbVersion.log   
