#!/bin/bash

# rewrite of renew_pdb_full
# this script works based on the pdb table in the mysql database
# (-> extracting SEQRES and redundancy reduction are delegated to the database import)
# it writes the output a3m files to the cache and also adds psipred a3m files to the chache
# then it collects the current psipred a3m files to a directory that hhblitsdb.pl can work on

if [ -z "$conf_file" ]; then
	conf_file='/etc/pssh2.conf'
fi

usage()
{
cat << EOT
NAME
  make_new_pdb_full - generate a new pdb_full database 
SYNOPSIS
  make_new_pdb_full [-u|-r]  [-v (verbose)] [-d dbName] 
DESCRIPTION
  make_new_pdb_full iterates over sequences in the pdb table of Aquaria,
  writes pdb_redundant_chains-md5-seq-mapping,
  runs build_hhblits_profile for each sequence (to get a3m files),
  runs addss.pl on each a3m file,
  links the output a3m files to the psipred a3m directory
  and finally runs hhblitsdb.pl on the psipred a3m directory
OPTIONS
  -u          update:  
  -r          regenerate: force remake a3m files 
  -f          input sequence file (fasta format)
  -m          output file name for HMM (hhm format)
  -a          output file name for multiple sequence alignment (a3m format)
  -r          output file name for hhblits result file (hhr format)
  -b          big job -> run with more memory ($bigMem Gb) and residues ($bigRes) 
  -u          /path/to/uniprot_20_files (without extensions)
  -c          number of cpus hhblits should run in parallel (default $n_cpu)
AUTHOR
  Andrea Schafferhans <andrea.schafferhans@rostlab.org>
EOT
exit 1
}
