#!/bin/bash

# rewrite of renew_pdb_full
# this script works based on the pdb table in the mysql database
# (-> extracting SEQRES and redundancy reduction are delegated to the database import)
# it writes the output a3m files to the cache and also adds psipred a3m files to the chache
# then it collects the current psipred a3m files to a directory that hhblitsdb.pl can work on

if [ -z "$conf_file" ]; then
	conf_file='/etc/pssh2.conf'
fi

usage()
{
cat << EOT
NAME
  make_new_pdb_full - generate a new pdb_full database 
SYNOPSIS
  build_hhblits_profile <-f fasta_sequence_file> <-m hmm_file_name> <-a a3m_file_name> 
          <-r results_file_name> [-b] [-u /path/to/uniprot_20] [-s] [-c number_of_cpus]
DESCRIPTION
  build_hhblits_profile takes an input sequence,
  searches against the uniprot20 database of HMMs 
  and generates a HHM output (HMM-profile) as well as 
  an a3m file of the alignment and
  a result file containing details of the search
  The databases to search with hhblits should be available under $u20
  unless they are explicitly given in the input.
  Defaults are configured in $conf_file.
OPTIONS
  -h          The option -h displays help and exits.
  -s          Operate silently 
  -f          input sequence file (fasta format)
  -m          output file name for HMM (hhm format)
  -a          output file name for multiple sequence alignment (a3m format)
  -r          output file name for hhblits result file (hhr format)
  -b          big job -> run with more memory ($bigMem Gb) and residues ($bigRes) 
  -u          /path/to/uniprot_20_files (without extensions)
  -c          number of cpus hhblits should run in parallel (default $n_cpu)
AUTHOR
  Andrea Schafferhans <andrea.schafferhans@rostlab.org>
EOT
exit 1
}
