#!/bin/bash

usage()
{
cat <<EOF
 EOT
NAME
  find_cache_path - generate full path to the cache for a given md5 sum (or a list of md5 sums)
SYNOPSIS
  pssh2_multi_md5 [-h] [-D] [-m \"md5 input list\"] [-- ...]
DESCRIPTION
  pssh2_multi_md5 takes md5 sums from the command line (behind -m),
  gets the associated sequences from the database,
  and runs pssh2 for each of the sequences (which adds the alignment to the database).
  See pssh2_seq -h for more details on pssh2_seq.
  Defaults are configured in $conf_file.
OPTIONS
  -h          The option -h displays help and exits.
  -D          Debug option: do not remove or zip output files (passed on to pssh2_seq)
  Any other parameters behind "--" are passed on to the child scripts.
AUTHOR
  Andrea Schafferhans <andrea.schafferhans@rostlab.org>
EOT
}

EOF

while getopts :hm: opt
do
        case $opt in
        h) usage; echo " "; pssh2_seq -h; exit;;
        m) md5list=$OPTARG;;
#       *) passOpt="$passOpt $OPTARG";;
        esac
done

pssh2_cache="/mnt/project/psshcache/result_cache_2014/"

for md5 in $md5list
do
	# get subdir names for cache structure
	M=`echo $md5|cut -b1,2`
	M2=`echo $md5|cut -b3,4`

	### full path to cachedir
	CC="$pssh2_cache$M/$M2/$md5"
	echo $CC

done
