#!/bin/bash

### uses a different cache dir root than predictprotein but the same tree/prefix structure
### runs things that should be integrated into PP soon but withoout polluting the ppcache

#$ -o /dev/null
#$ -e /dev/null

#set -x

### base path to all caches
#### ex /mnt/project/snapcache/andrea_pssh/ppcache22/bd/38/
C="/mnt/project/snapcache/andrea_pssh/all_caches/"
H="/mnt/project/pssh/pssh2_project/data/uniprot_derived/hhblits_hmms/

M="/mnt/project/mamut";
DB="/var/tmp/rost_db/data";
T="/tmp/mamut"
PS="/mnt/project/pssh/pssh2_project/work/sequences_missingInMamut_20140910/"

for i in $* ; do
### get fasta and tmpdir block
	mkdir -p $T/$i  2>/dev/null
	chmod 777 $T  $T/$i 
	[ -s $T/$i/$i.fasta ] ||    $M/bin/get_fasta_4db $i

	if [ -s $T/$i/$i.fasta ] ; then
    
### get seq/md5/ppc from db	
		seq=`/mnt/home/roos/bin/DB.idmapper "select seq from idmapper.md5_ppc_len_seq where  md5=\"$i\" or  ppc=\"$i\" "|grep -v "^seq$"`
		ppc=`/mnt/home/roos/bin/DB.idmapper "select ppc from idmapper.md5_ppc_len_seq where  md5=\"$i\" or  ppc=\"$i\" "|grep -v "^ppc$"`
		md5=`/mnt/home/roos/bin/DB.idmapper "select md5 from idmapper.md5_ppc_len_seq where  md5=\"$i\" or  ppc=\"$i\" "|grep -v "^md5$"`

### build prefixes for ppc/extracache
		P=`echo $ppc|cut -b1,2`
		P2=`echo $ppc|cut -b3,4`
### build prefixes for md5/extracache
		M=`echo $md5|cut -b1,2`
		M2=`echo $md5|cut -b3,4`
		echo $ppc $P $P2 $md5 $M $M2

### full path to cachedir
		CC="$C$P/$P2/$ppc"
		HH="$H$M/$M2"
		echo $CC $HH

### create hmmdir if not existent
		mkdir -p $HH
		if [ -d $HH] ; then
			$hhm_file="$CC/query.hhm" 
			if [ -s $hmm_file ] ; then
				timeStamp=`stat -c%Y $hhm_file`  
				DB.pssh2_local "insert into pssh2_local.swissprot_hhm set md5=\"$md5\" , stamp=$timeStamp , hhm_path=\"$CC\"" 
				ln -s $hhm_file $HH/$md5.hhm
			fi
		else 
			echo "ERROR: was not able to write to $HH please go fix"
		fi
	else
		echo "ERROR: could not find sequence: $T/$i/$i.fasta"
	fi

done
