#!/bin/bash

while getopts :hm: opt
do
        case $opt in
        h) usage; echo " "; pssh2_seq -h; exit;;
        m) md5list=$OPTARG;;
#       *) passOpt="$passOpt $OPTARG";;
        esac
done

pssh2_cache="/mnt/project/psshcache/result_cache_2014/"

for md5 in $md5list
do
	# get subdir names for cache structure
	M=`echo $md5|cut -b1,2`
	M2=`echo $md5|cut -b3,4`

	### full path to cachedir
	CC="$pssh2_cache$M/$M2/$md5"
	echo $CC

done
