#!/bin/bash

usage()
{
cat <<EOT
NAME
  find_cache_path - generate full path to the cache for a given md5 sum (or a list of md5 sums)
SYNOPSIS
  find_cache_path [-h] [-m \"md5 input list\"] 
DESCRIPTION
  find_cache_path takes md5 sums from the command line (behind -m),
  and returns the corresponding path(s)
OPTIONS
  -h          The option -h displays help and exits.
AUTHOR
  Andrea Schafferhans <andrea.schafferhans@rostlab.org>
EOT
}



while getopts :hm: opt
do
        case $opt in
        h) usage; echo " "; exit;;
        m) md5list=$OPTARG;;
#       *) passOpt="$passOpt $OPTARG";;
        esac
done

pssh2_cache="/mnt/project/psshcache/result_cache_2014/"

for md5 in $md5list
do
	# get subdir names for cache structure
	M=`echo $md5|cut -b1,2`
	M2=`echo $md5|cut -b3,4`

	### full path to cachedir
	CC="$pssh2_cache$M/$M2/$md5"
	echo $CC

done
