#!/bin/bash
### get fasta files from the db aquaria.protein_sequence   works on md5s 

conf_file='/etc/pssh2.conf'

### work directory
temp_work="/tmp/pssh2"


# get configurable options, e.g. local file paths
if [ -s $conf_file ]
then
	source $conf_file
fi

usage()
{
cat << EOT
NAME
  get_fasta_for_md5 - create a md5.fasta file for each given md5 hash 
SYNOPSIS
  get_fasta_for_md5 md5_hash1 [ md5_hash2 ... ] 
DESCRIPTION
  get_fasta_for_md5 takes one or more input sequence md5 hash(es) and writes out 
  one or more fasta files in dedicated subdirectories $temp_work/md5/. 
  The sequence information comes from the protein_sequence table in the aquaria mysql 
  database.
  The credentials for querying the database are stored in DB.aquaria_local script.
  The input scripts for the aquaria database is found in the Aquaria project.
AUTHOR
  Andrea Schafferhans <andrea.schafferhans@rostlab.org>
EOT
}


for md5 in $* 
do
	mkdir -p $temp_work/$md5  2>/dev/null
	seq = `DB.aquaria_local "select Sequence from protein_sequence where MD5_hash =\"$md5\" " `
	echo -e ">$md5\n$seq" > $temp_work/$md5/$md5.fasta 
	echo "$temp_work/$md5/$md5.fasta"
done