#!/bin/bash

# this script is used to sum up the parameters for a profile building hhblits in one place
# it is used by pp_pssh2 (for PredictProtein) and by the generate_pssh2 perl script

u20='/var/tmp/rost_db/data/hhblits/uniprot20_current'
#u20='/usr/share/hhblits/uniprot20_current'
big=''
reportedHits=" -B 10000 -Z 10000"
hhblitsLog='hhblits.log'

# get configurable options, e.g. local file paths
if [ -s pssh2.cfg ]
then
	source pssh2.cfg
fi

usage()
{
cat << EOT
NAME
  build_hhblits_profile - generate a hhblits HHM (called hhm) by scanning against uniprot_20 
SYNOPSIS
  pssh2_seq <-f fasta sequence file> <-m hmm file name> <-a a3m file name> <-r results file name> 
  [-b] [-u /path/to/uniprot_20] [-s]
DESCRIPTION
  build_hhblits_profile takes an input sequence,
  searches against the uniprot20 database of HMMs 
  and generates a HHM output (HMM-profile) as well as 
  an a3m file of the alignment and
  a result file containing details of the search
  The databases to search with hhblits should be available under $u20
  unless they are explicitly given in the input.
OPTIONS
  -h          The option -h displays help and exits.
  -s          Operate silently 
  -f          input sequence file (fasta format)
AUTHOR
  Andrea Schafferhans <andrea.schafferhans@rostlab.org>
EOT
}



usage() { 
	echo "Usage: $0 -f <fasta sequence file> -m <hmm file name> -a <a3m file name> -r <results file name>" 
	echo "                           [-b (for much memory)] [-u /path/to/uniprot_20 (without extensions)] [-s (silent)]"
	echo "                           (default path: $u20)" 1>&2
	exit 1; 
}


while getopts "f:m:a:r:bu:hs" option;
do
 case $option in
  f)
   # expects fasta formatted input file
   fasta=$OPTARG;
   hhblitsLog=$fasta.$hhblitsLog
   ;;
  m)
   # name of output file for hmm 
   hhm=$OPTARG;
   ;;
  a)
   # name of output file for a3m 
   a3m=$OPTARG;
   ;;
  r)
   # name of output file for hhblits results  
   hhr=$OPTARG;
   ;;
  u)
   # path for uniprot_20 for hhblits
   u20=$OPTARG;
   ;;
  b)
	echo 'received -b, setting option -maxmem 5'
  	b='-maxmem 5 '
   ;;
  :)
   echo "option -$OPTARG needs an argument"
   usage
   ;;
  h)
   usage  	
   ;;
  s)
   hhblitsLog='/dev/null'  	
   ;;
  *)
   echo "invalid option -$OPTARG" 
   usage
   ;;
 esac
done

if  [ -z "$fasta" -o -z "$hhm" -o -z "$a3m" -o -z "$hhr" ]; 
then
	usage
fi

#echo "running hhblits -cpu 1 -i $fasta -d $u20 -ohhm $hhm -oa3m $a3m -o $hhr $b $reportedHits"
hhblits -cpu 1 -i $fasta -d $u20 -ohhm $hhm -oa3m $a3m -o $hhr $b $reportedHits >> $hhblitsLog




