#!/bin/bash

### runs pssh2 for a set of md5 sums
#$ -o /dev/null
#$ -e /dev/null

#set -x

if [ -z "$conf_file" ]; then
	conf_file='/etc/pssh2.conf'
fi

usage()
{
cat << EOT
NAME
  pssh2_aws - generate pssh2 type sequence-to-structrue alignments for many sequences on AWS
SYNOPSIS
  pssh2_aws [-h] [-D] [-- ...]
DESCRIPTION
  pssh2_aws runs until terminated or until no more md5 sums need to be processed. 
  It (repeatedly) queries for md5 sums to process,
  for each md5 it
  - gets corresponding cache entries from S3,
  - gets the associated sequences from the database,
  - runs pssh2_seq (which adds the alignment to the database),
  - stores the result files in S3.
  See pssh2_seq -h for more details on pssh2_seq.
  Defaults are configured in $conf_file.
OPTIONS
  -h          The option -h displays help and exits.
  -D          Debug option: do not remove or zip output files (passed on to pssh2_seq)
  Any other parameters behind "--" are passed on to the child scripts.
AUTHOR
  Andrea Schafferhans <andrea.schafferhans@rostlab.org>
EOT
}


