#!/bin/bash
## run the necessary things for pssh2 predictions
### run and parse hhblits

if [ -z "$conf_file" ]; then
	conf_file='/etc/pssh2.conf'
fi

usage()
{
cat << EOT
NAME
  pp_pssh2 - generate pssh2 type sequence-to-structrue alignments for PredictProtein
SYNOPSIS
  pp_pssh2 [-h] [-- ...]
DESCRIPTION
  wrapper around pssh2_seq: 
  operates silently (sets -s) 
  and writes to mysql table pssh2_pp (sets tableName to pssh2_pp),
  also communicates with the cache (getting data, storing data).
  Any other parameters behind "--" are passed on to the child scripts.
AUTHOR
  Andrea Schafferhans <andrea.schafferhans@rostlab.org>
EOT
}

### base path to cache
pssh2_cache="/mnt/project/psshcache/result_cache_2014/"
# get configurable options, e.g. local file paths
if [ -s $conf_file ]
then
	source $conf_file
fi


silent=1
passOpt=" " 
while getopts :h opt
do
	case $opt in
	h) usage; echo " "; pssh2_seq -h; exit;;
#	*) passOpt="$passOpt -$opt";;
	esac
done
shift $(expr $OPTIND - 1 )
passOpt=$@

pssh2_seq -s -t pssh2_pp $passOpt

# possibly delete more files... 