#!/bin/bash

# this script is used to sum up the parameters for a structure database (pdb_full) scanning hhblits in one place
# it is used by the PredictProtein make file and by the generate_pssh2 perl script

pdb_full='/var/tmp/rost_db/data/hhblits/pdb_full'
#pdb_full='/usr/share/hhblits/pdb_full'
big=''
reportedHits=" -B 10000 -Z 10000"
hhblitsLog='hhblits.log'

usage() { 
	echo "Usage: $0 -m <hmm input file name> -r <results file name>" 
	echo "                           [-b (for much memory)] [-p /path/to/pdb_full (without extensions)]"
	echo "                           (default path: $pdb_full)" 1>&2
	exit 1; }

### uniprot20 location
u20='/var/tmp/rost_db/data/hhblits/uniprot20_current'
#u20='/usr/share/hhblits/uniprot20_current'
### amount of memory to use for big jobs
bigMem=5
### parallel runs
$n_cpu=1

reportedHits=" -B 10000 -Z 10000"
hhblitsLog='hhblits.log'

# get configurable options, e.g. local file paths
if [ -s pssh2.cfg ]
then
	source pssh2.cfg
fi

usage()
{
cat << EOT
NAME
  build_hhblits_profile - generate a hhblits HHM (called hhm) by scanning against uniprot_20 
SYNOPSIS
  pssh2_seq <-f fasta sequence file> <-m hmm file name> <-a a3m file name> <-r results file name> 
  [-b] [-u /path/to/uniprot_20] [-s] [-p number_of_cpus]
DESCRIPTION
  build_hhblits_profile takes an input sequence,
  searches against the uniprot20 database of HMMs 
  and generates a HHM output (HMM-profile) as well as 
  an a3m file of the alignment and
  a result file containing details of the search
  The databases to search with hhblits should be available under $u20
  unless they are explicitly given in the input.
OPTIONS
  -h          The option -h displays help and exits.
  -s          Operate silently 
  -f          input sequence file (fasta format)
  -m          output file name for HMM (hhm format)
  -a          output file name for multiple sequence alignment (a3m format)
  -r          output file name for hhblits result file (hhr format)
  -b          big job -> run with more memory ($bigMem) 
  -u          /path/to/uniprot_20_files (without extensions)
  -s          operate silently
  -p          number of cpus hhblits should run in parallel (default $n_cpu)
AUTHOR
  Andrea Schafferhans <andrea.schafferhans@rostlab.org>
EOT
exit 1
}



while getopts "m:r:p:bu:hs" option;
do
 case $option in
  m)
   # name of input hmm profile (generated e.g. with bild_hhblits_profile.sh)
   hhm=$OPTARG;
   hhblitsLog=$hhm.$hhblitsLog
   ;;
  r)
   # name of output file for hhblits results  
   hhr=$OPTARG;
   ;;
  p)
   # path for pdb_full for hhblits
   pdb_full=$OPTARG;
   ;;
  b)
	echo 'received -b, setting option -maxmem 5'
  	b='-maxmem 5 '
   ;;
  :)
   echo "option -$OPTARG needs an argument"
   usage
   ;;
  h)
   usage  	
   ;;
  s)
   hhblitsLog='/dev/null'
   ;;
  *)
   echo "invalid option -$OPTARG" 
   usage
   ;;
 esac
done

if  [ -z "$hhm" -o -z "$hhr" ]; 
then
	usage
fi

#echo "running hhblits -cpu 1 -i $hhm -d $pdb_full  -n 1 -o $hhr $b $reportedHits"
hhblits -cpu 1 -i $hhm -d $pdb_full  -n 1 -o $hhr $b $reportedHits >> $hhblitsLog




